"""Mechanical enforcement: nova MUST NOT reference ali-kernel or ornith.

Run via pytest (`pytest backend/tests/test_no_cross_references.py -v`) or
directly (`python3 backend/tests/test_no_cross_references.py`).

Forbidden strings (any case variation):
  - ali-kernel, ali_kernel, ali kernel, ali-kernl, etc.
  - ornith (in comments, identifiers, doc strings — but the model file
    path /home/jahanzaib/ornith-*.gguf is allowed since that's a real
    filename on disk)

Allowed:
  - "DeerFlow" / "deer-flow" / "deerflow" — these are SELF references
    (Nova was renamed from DeerFlow); they're the project history,
    not a cross-project coupling.
  - The `deerflow` Python package namespace (e.g. `from deerflow.x import
    y`) — that's the package import path, not a project reference.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Files to skip entirely (they contain the rule definitions themselves,
# or are the rule's data)
SKIP_FILES = {
    "AGENTS.md",
    "CLAUDE.md",
    "backend/CLAUDE.md",
    "frontend/CLAUDE.md",
    "backend/tests/test_no_cross_references.py",  # contains forbidden strings as test data
    "scripts/fix_cross_references.py",  # contains forbidden strings in rename table
    "scripts/check_no_cross_references.sh",  # wrapper that mentions the names
}

# Forbidden strings (case-insensitive matching)
FORBIDDEN = [
    "ali-kernel",     # the service we don't couple to
    "ali_kernel",     # underscored variant
    "ali kernel",     # space variant
    "ornith",         # the model name (ali-kernel-specific)
]

# Allow-list for known-acceptable references (very few — nova is mostly clean)
ALLOW_LIST: list[tuple[str, re.Pattern[str], str]] = [
    # The runtime_models.yaml has the actual GGUF model path (file name on disk)
    # — that path legitimately contains "ornith" because the GGUF is named that.
    # Gitignored so this only matters if someone runs the test after we wrote it.
    (
        "backend/.deer-flow/runtime_models.yaml",
        re.compile(r"ornith"),
        "Runtime model YAML points at the actual GGUF file on disk; file "
        "name is 'ornith-1.0-9b-Q4_K_M.gguf'. Gitignored; would be "
        "regenerated by the gateway API.",
    ),
]


def _gather_files() -> list[Path]:
    """Collect all files to scan via `git ls-files` (respects .gitignore)."""
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    files = []
    for line in result.stdout.splitlines():
        if not line:
            continue
        path = REPO_ROOT / line
        if not path.is_file():
            continue
        if any(part.startswith(".") for part in path.parts):
            continue  # skip .git, .opencode, etc.
        rel = str(path.relative_to(REPO_ROOT))
        if rel in SKIP_FILES:
            continue
        files.append(path)
    return files


def _is_allowed(rel: str, line: str) -> bool:
    for allowed_path, pattern, _reason in ALLOW_LIST:
        if allowed_path == rel and pattern.search(line):
            return True
    return False


def _scan_file(path: Path) -> list[tuple[int, str, str]]:
    """Return (line_no, forbidden_string, line_text) for each violation.

    ornith is allowed when it appears inside a string literal (e.g.
    `"Ornith (local)"` as a UI placeholder, or `"ornith"` as a model id).
    Code references — identifiers and comments — are flagged.
    """
    violations: list[tuple[int, str, str]] = []
    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return violations

    rel = str(path.relative_to(REPO_ROOT))

    # Heuristic: does this line have ornith inside a string literal?
    # Match: "ornith...", 'ornith...', "...ornith...", "...ornith'",
    # `ornith...`, etc. (any quote type, content may span the substring).
    STRING_LITERAL_RE = re.compile(
        r"""(['"`])[^'"`]*ornith[^'"`]*\1""",
        re.IGNORECASE,
    )

    for lineno, line in enumerate(content.splitlines(), start=1):
        if _is_allowed(rel, line):
            continue
        line_lower = line.lower()

        # Skip ali-kernel checks for everything (no string-literal allowance)
        for forbidden in ("ali-kernel", "ali_kernel", "ali kernel"):
            if forbidden in line_lower:
                violations.append((lineno, forbidden, line.strip()))

        # ornith: allowed inside a string literal on the same line
        if "ornith" in line_lower:
            if STRING_LITERAL_RE.search(line):
                # The forbidden occurrence is inside a quoted string — allow
                continue
            violations.append((lineno, "ornith", line.strip()))

    return violations


def main() -> int:
    print(f"Scanning {REPO_ROOT} for cross-project references...")
    print()

    files = _gather_files()
    total_violations = 0
    files_with_violations: dict[Path, list[tuple[int, str, str]]] = {}

    for path in files:
        violations = _scan_file(path)
        if violations:
            files_with_violations[path] = violations
            total_violations += len(violations)

    if not files_with_violations:
        print("OK: no cross-project references found.")
        print(f"  Scanned {len(files)} files.")
        return 0

    print(f"FAIL: {total_violations} cross-project reference(s) in {len(files_with_violations)} file(s):")
    print()
    for path, violations in files_with_violations.items():
        rel = path.relative_to(REPO_ROOT)
        for lineno, forbidden, line in violations:
            print(f"  {rel}:{lineno}: {forbidden}")
            print(f"    {line[:100]}{'...' if len(line) > 100 else ''}")
        print()

    print("Remediation:")
    print("  - For ali-kernel: rename variable/function/module to something generic")
    print("  - For ornith in code/comments: rewrite or move to config")
    print()
    print("Auto-fix: python3 scripts/fix_cross_references.py --dry-run")
    print("Allow-list: edit SKIP_FILES / ALLOW_LIST in backend/tests/test_no_cross_references.py")

    return 1


if __name__ == "__main__":
    sys.exit(main())
