apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      timeInterval: 15s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    editable: false
    jsonData:
      timeout: 10s
      derivedFields:
        - name: trace_id
          matcherRegex: '"trace_id":"([^"]+)"'
          url: https://nova.alilabsx.com/api/traces/${__value}
          datasourceUid: tempo
