apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-nginx-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nova.labels" . | nindent 4 }}
data:
  nginx.conf: |-
{{ tpl (.Files.Get "files/nginx.conf") . | indent 4 }}
