apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nova-provisioner
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nova.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "get", "list", "delete"]
