/**
 * Phase C0.7 — cross-process correlation integration test.
 *
 * This test simulates the production wire format exactly: the backend
 * emits a ``: correlation_id=<hex>\n\n`` comment as the first SSE frame
 * via a streaming ReadableStream, and the frontend's ``livenessFetch``
 * (specifically the ``wrapBody`` body decoder) must capture it before
 * any other SSE frame is processed.
 *
 * If this test passes, an end-to-end trace correlation works: a single
 * identifier is generated by the backend ``RunManager.create()``,
 * emitted on the SSE stream, captured by the frontend, and readable via
 * ``getCorrelationId(threadId)`` for every subsequent stream-trace
 * record.
 *
 * The Python-side counterpart is ``backend/tests/integration/test_correlation_e2e.py``
 * which builds an ``httpx.AsyncClient`` against a live ``TestClient`` and
 * asserts the correlation_id is present in the SSE wire format.
 */

import { ReadableStream } from "node:stream/web";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  captureCorrelationIdFromChunk_FOR_TESTING,
  getCorrelationId,
  resetCorrelationIds,
} from "@/core/api/stream-liveness";

beforeEach(() => {
  resetCorrelationIds();
});

afterEach(() => {
  resetCorrelationIds();
});

/**
 * Build an SSE wire-format chunk stream exactly as the backend emits it.
 * Each chunk is one or more complete SSE frames so the test is independent
 * of chunk-boundary heuristics.
 */
function sseStream(frames: string[]): ReadableStream<Uint8Array> {
  const encoder = new TextEncoder();
  let i = 0;
  return new ReadableStream<Uint8Array>({
    pull(controller) {
      if (i >= frames.length) {
        controller.close();
        return;
      }
      controller.enqueue(encoder.encode(frames[i]));
      i += 1;
    },
  });
}

describe("cross-process correlation_id round-trip (Phase C0)", () => {
  it("captures the correlation_id emitted as the first SSE frame", () => {
    const decoder = new TextDecoder("utf-8");
    const frames = [
      ": correlation_id=abc12345-6789-0abc-def0-1234567890ab\n\n",
      'event: metadata\ndata: {"run_id":"run-1","thread_id":"thread-1"}\n\n',
      'event: messages\ndata: {"id":"msg-1","type":"human"}\n\n',
    ];
    const stream = sseStream(frames);

    const reader = stream.getReader();
    const threadId = "thread-1";
    let capturedAfterFirstChunk: string | null = null;

    return (async () => {
      const first = await reader.read();
      expect(first.done).toBe(false);
      captureCorrelationIdFromChunk_FOR_TESTING(
        threadId,
        first.value!,
        decoder,
      );
      capturedAfterFirstChunk = getCorrelationId(threadId);
      expect(capturedAfterFirstChunk).toBe(
        "abc12345-6789-0abc-def0-1234567890ab",
      );

      // Subsequent chunks must not change the captured value (idempotency).
      const second = await reader.read();
      captureCorrelationIdFromChunk_FOR_TESTING(
        threadId,
        second.value!,
        decoder,
      );
      expect(getCorrelationId(threadId)).toBe(
        "abc12345-6789-0abc-def0-1234567890ab",
      );

      const third = await reader.read();
      captureCorrelationIdFromChunk_FOR_TESTING(
        threadId,
        third.value!,
        decoder,
      );
      expect(getCorrelationId(threadId)).toBe(
        "abc12345-6789-0abc-def0-1234567890ab",
      );

      const done = await reader.read();
      expect(done.done).toBe(true);
    })();
  });

  it("uses thread_id derived from the URL, not from the wire body", () => {
    const decoder = new TextDecoder("utf-8");
    const stream = sseStream([
      ": correlation_id=from-thread-extraction\n\n",
      "event: metadata\ndata: {}\n\n",
    ]);

    return (async () => {
      const reader = stream.getReader();
      const chunk = (await reader.read()).value!;
      // Phase C0 uses the thread_id extracted from the request URL — the
      // SSE wire itself does NOT include a thread_id in the correlation
      // comment (it's keyed on the URL because the body decoder doesn't
      // know the request). This test verifies the capture path uses the
      // thread_id argument passed in.
      captureCorrelationIdFromChunk_FOR_TESTING(
        "thread-from-url",
        chunk,
        decoder,
      );
      expect(getCorrelationId("thread-from-url")).toBe(
        "from-thread-extraction",
      );
    })();
  });

  it("supports the SSE heartbeat comment without overwriting correlation_id", () => {
    const decoder = new TextDecoder("utf-8");
    const stream = sseStream([
      ": correlation_id=primary\n\n",
      ": heartbeat\n\n",
      ": heartbeat\n\n",
    ]);

    return (async () => {
      const reader = stream.getReader();
      const threadId = "thread-hb";

      // First chunk captures correlation_id.
      const first = (await reader.read()).value!;
      captureCorrelationIdFromChunk_FOR_TESTING(threadId, first, decoder);
      expect(getCorrelationId(threadId)).toBe("primary");

      // Subsequent heartbeat comments must NOT replace the captured value.
      const second = (await reader.read()).value!;
      captureCorrelationIdFromChunk_FOR_TESTING(threadId, second, decoder);
      expect(getCorrelationId(threadId)).toBe("primary");

      const third = (await reader.read()).value!;
      captureCorrelationIdFromChunk_FOR_TESTING(threadId, third, decoder);
      expect(getCorrelationId(threadId)).toBe("primary");
    })();
  });

  it("different threads get independent correlation_ids", () => {
    const decoder = new TextDecoder("utf-8");
    const stream = sseStream([
      ": correlation_id=thread-a-id\n\n",
      "event: messages\ndata: {}\n\n",
      ": correlation_id=thread-b-id\n\n",
      "event: messages\ndata: {}\n\n",
    ]);

    return (async () => {
      const reader = stream.getReader();

      // Stream chunk 1 — thread-a correlation_id.
      const chunk1 = (await reader.read()).value!;
      captureCorrelationIdFromChunk_FOR_TESTING("thread-a", chunk1, decoder);
      expect(getCorrelationId("thread-a")).toBe("thread-a-id");

      // Stream chunk 2 — thread-a chunk (no comment, idempotency check).
      const chunk2 = (await reader.read()).value!;
      captureCorrelationIdFromChunk_FOR_TESTING("thread-a", chunk2, decoder);
      expect(getCorrelationId("thread-a")).toBe("thread-a-id");

      // Stream chunk 3 — thread-b correlation_id.
      const chunk3 = (await reader.read()).value!;
      captureCorrelationIdFromChunk_FOR_TESTING("thread-b", chunk3, decoder);
      expect(getCorrelationId("thread-b")).toBe("thread-b-id");

      // Stream chunk 4 — thread-b chunk.
      const chunk4 = (await reader.read()).value!;
      captureCorrelationIdFromChunk_FOR_TESTING("thread-b", chunk4, decoder);
      expect(getCorrelationId("thread-b")).toBe("thread-b-id");

      // Independence: thread-a unchanged.
      expect(getCorrelationId("thread-a")).toBe("thread-a-id");
    })();
  });

  it("handles chunk that spans the boundary between two SSE frames", () => {
    const decoder = new TextDecoder("utf-8");
    // A single chunk contains BOTH the correlation_id comment AND part of
    // the next event. The capture path must still pick up the comment.
    const encoder = new TextEncoder();
    const splitChunk = encoder.encode(
      ": correlation_id=split\n\nevent: metadata\ndata: {}\n",
    );
    const stream = new ReadableStream<Uint8Array>({
      start(controller) {
        controller.enqueue(splitChunk);
        controller.close();
      },
    });

    return (async () => {
      const reader = stream.getReader();
      const chunk = (await reader.read()).value!;
      captureCorrelationIdFromChunk_FOR_TESTING("thread-split", chunk, decoder);
      expect(getCorrelationId("thread-split")).toBe("split");
    })();
  });
});
